- name: Install Debian Apache
  apt:
    name: apache2
    state: present

- name: Start Debian Apache
  systemd:
    state: started
    name: apache2
    enabled: yes

- name: Install Unzip unpacker (using module) 
  ansible.builtin.apt:
    name: unzip

- name: Fetch template archive
  ansible.builtin.get_url:
    url: https://www.free-css.com/assets/files/free-css-templates/download/page281/john-doe.zip
    dest: /tmp/

- name: Unarchive template files
  ansible.builtin.unarchive:
    src: /tmp/john-doe.zip 
    dest: /tmp/
    remote_src: yes  

- name: Copy template files to the server /var/www/html (using module)
  ansible.builtin.copy:
    src: /tmp/johndoe/public_html/
    dest: /var/www/html
    remote_src: yes  

 #eof   